app-configuration:
  name: naver
  applications:
    bluebox: config/naver-bluebox-prd.yaml
    #bluebox: config/naver-bluebox-dev.yaml
    #bluebox2: config/naver-bluebox2.yaml

server:
  port: 8080

http:
  connectTimeout: 10
  responseTimeout: 180

spring:
  devtools:
    livereload:
      enabled: true
  quartz:
    scheduler-name: QuartzScheduler
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 10
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: cloudedi.noreply@gmail.com
    password: frprunjxztsbxova
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 5000
  profile:
    active: local

jasypt:
  encryptor:
    bean: encryptorBean


logging:
  config: config/logback-spring.xml

